/*! hdate-he 3.4.7 */
!function(){"use strict";
/*! @hebcal/hdate v0.21.1, distributed under GPLv2 https://www.gnu.org/licenses/gpl-2.0.txt */const t=[0,31,28,31,30,31,30,31,31,30,31,30,31],e=[t,t.slice()];function n(t,e){return t-e*Math.floor(t/e)}function r(t,e){return Math.floor(t/e)}function o(t){return!(t%4||!(t%100)&&t%400)}function a(t){return"object"==typeof t&&Date.prototype.isPrototypeOf(t)}function s(t,e,n){const a=t-1;return 365*a+r(a,4)-r(a,100)+r(a,400)+r(367*e-362,12)+(e<=2?0:o(t)?-1:-2)+n}function c(t){if(!a(t))throw new TypeError(`not a Date: ${t}`);if(isNaN(t.getTime()))throw new RangeError("Invalid Date");return s(t.getFullYear(),t.getMonth()+1,t.getDate())}
/*! @hebcal/hdate v0.21.1, distributed under GPLv2 https://www.gnu.org/licenses/gpl-2.0.txt */
function i(t){return t.normalize().replace(/[\u0590-\u05bd]/g,"").replace(/[\u05bf-\u05c7]/g,"")}
/*! @hebcal/hdate v0.21.1, distributed under GPLv2 https://www.gnu.org/licenses/gpl-2.0.txt */e[1][2]=29;const u=12,l=new Map,f=-1373428;function h(t,e){if("number"!=typeof t||isNaN(t))throw new TypeError(`param '${e}' not a number: ${t}`)}function p(t,e,n){if(h(t,"year"),h(e,"month"),h(n,"day"),t<1)throw new RangeError(`hebrew2abs: invalid year ${t}`);let r=n;if(e<7){for(let e=7;e<=g(t);e++)r+=w(e,t);for(let n=1;n<e;n++)r+=w(n,t)}else for(let n=7;n<e;n++)r+=w(n,t);return f+m(t)+r-1}function d(t){return f+m(t)}function y(t){return(1+7*t)%19<7}function g(t){return+y(t)+12}function w(t,e){switch(t){case 2:case 4:case 6:case 10:case 13:return 29}return 12===t&&!y(e)||8===t&&!function(t){return b(t)%10==5}(e)||9===t&&function(t){return b(t)%10==3}
/*! @hebcal/hdate v0.21.1, distributed under GPLv2 https://www.gnu.org/licenses/gpl-2.0.txt */(e)?29:30}function m(t){const e=l.get(t);if("number"==typeof e)return e;const n=function(t){const e=t-1,n=235*Math.floor(e/19)+e%19*12+Math.floor((e%19*7+1)/19),r=204+n%1080*793,o=5+12*n+793*Math.floor(n/1080)+Math.floor(r/1080),a=r%1080+o%24*1080,s=1+29*n+Math.floor(o/24);let c=s;(a>=19440||2==s%7&&a>=9924&&!y(t)||1==s%7&&a>=16789&&y(e))&&c++;return c%7==0||c%7==3||c%7==5?c+1:c}(t);return l.set(t,n),n}function b(t){return m(t+1)-m(t)}var v;v||(v={}),v.abs2greg=function(t){if("number"!=typeof t||isNaN(t))throw new TypeError(`not a Number: ${t}`);const e=function(t){const e=t-1,o=r(e,146097),a=n(e,146097),s=r(a,36524),c=n(a,36524),i=r(c,1461),u=r(n(c,1461),365),l=400*o+100*s+4*i+u;return 4!==s&&4!==u?l+1:l}(t=Math.trunc(t)),a=r(12*(t-s(e,1,1)+(t<s(e,3,1)?0:o(e)?1:2))+373,367),c=t-s(e,a,1)+1,i=new Date(e,a-1,c);return e<100&&e>=0&&i.setFullYear(e),i},v.daysInMonth=function(t,n){return e[+o(n)][t]},v.greg2abs=c,v.isDate=a,v.isLeapYear=o;
/*! @hebcal/hdate v0.21.1, distributed under GPLv2 https://www.gnu.org/licenses/gpl-2.0.txt */
const T={"א":1,"ב":2,"ג":3,"ד":4,"ה":5,"ו":6,"ז":7,"ח":8,"ט":9,"י":10,"כ":20,"ל":30,"מ":40,"נ":50,"ס":60,"ע":70,"פ":80,"צ":90,"ק":100,"ר":200,"ש":300,"ת":400},N={};for(const[t,e]of Object.entries(T))N[e]=t;function k(t){const e=[];for(;t>0;){if(15===t||16===t){e.push(9),e.push(t-9);break}let n,r=100;for(n=400;n>t;n-=r)n===r&&(r/=10);e.push(n),t-=n}return e}function E(t){const e=parseInt(t,10);if(!e||e<0)throw new TypeError(`invalid number: ${t}`);let n="";const r=Math.floor(e/1e3);if(r>0&&5!==r){const t=k(r);for(const e of t)n+=N[e];n+="׳"}const o=k(e%1e3);if(1===o.length)return n+N[o[0]]+"׳";for(let t=0;t<o.length;t++)t+1===o.length&&(n+="״"),n+=N[o[t]];return n}
/*! @hebcal/hdate v0.21.1, distributed under GPLv2 https://www.gnu.org/licenses/gpl-2.0.txt */var L={headers:{"plural-forms":"nplurals=2; plural=(n > 1);",language:"he"},contexts:{"":{Adar:["אֲדָר"],"Adar I":["אֲדָר א׳"],"Adar II":["אֲדָר ב׳"],Av:["אָב"],Cheshvan:["חֶשְׁוָן"],Elul:["אֱלוּל"],Iyyar:["אִיָּיר"],Kislev:["כִּסְלֵו"],Nisan:["נִיסָן"],"Sh'vat":["שְׁבָט"],Sivan:["סִיוָן"],Tamuz:["תַּמּוּז"],Tevet:["טֵבֵת"],Tishrei:["תִּשְׁרֵי"]}}};
/*! @hebcal/hdate v0.21.1, distributed under GPLv2 https://www.gnu.org/licenses/gpl-2.0.txt */
/*! @hebcal/hdate v0.21.1, distributed under GPLv2 https://www.gnu.org/licenses/gpl-2.0.txt */
const M={headers:{"plural-forms":"nplurals=2; plural=(n!=1);"},contexts:{"":{}}},$={h:"he",a:"ashkenazi",s:"en","":"en"},x=new Map;function I(t){const e=["th","st","nd","rd"],n=t%100;return t+(e[(n-20)%10]||e[n]||e[0])}function j(t){if("string"!=typeof t)throw new TypeError(`Invalid locale name: ${t}`);return(t=$[t]||t).toLowerCase()}function A(t){const e=j(t),n=x.get(e);if(!n)throw new RangeError(`Locale '${t}' not found`);return n}class z{static lookupTranslation(t,e){const n=("string"==typeof e&&x.get(j(e))||M.contexts[""])[t];if((null==n?void 0:n.length)&&n[0].length)return n[0]}static gettext(t,e){const n=this.lookupTranslation(t,e);return void 0===n?t:n}static addLocale(t,e){t=j(t);const n=e.contexts;if("object"!=typeof n||"object"!=typeof n[""])throw new TypeError(`Locale '${t}' invalid compact format`);x.set(t,n[""])}static addTranslation(t,e,n){const r=A(t);if("string"!=typeof e||0===e.length)throw new TypeError(`Invalid id string: ${e}`);const o=Array.isArray(n);if(o){const t=n[0];if("string"!=typeof t||0===t.length)throw new TypeError(`Invalid translation array: ${n}`)}else if("string"!=typeof n)throw new TypeError(`Invalid translation string: ${n}`);r[e]=o?n:[n]}static addTranslations(t,e){const n=A(t),r=e.contexts;if("object"!=typeof r||"object"!=typeof r[""])throw new TypeError(`Locale '${t}' invalid compact format`);Object.assign(n,r[""])}static getLocaleNames(){return Array.from(x.keys()).sort((t,e)=>t.localeCompare(e))}static hasLocale(t){const e=j(t);return x.has(e)}static ordinal(t,e){let n=null==e?void 0:e.toLowerCase();if(!n)return I(t);switch(n=$[n]||n,n){case"en":case"ashkenazi":return I(t);case"es":return t+"º";case"he":case"he-x-nonikud":return String(t)}return n.startsWith("ashkenazi")?I(t):t+"."}static hebrewStripNikkud(t){return i(t)}static copyLocaleNoNikud(t){const e=t.contexts[""],n={};for(const[t,r]of Object.entries(e))n[t]=[i(r[0])];return{headers:t.headers,contexts:{"":n}}}}z.addLocale("en",M),z.addLocale("ashkenazi",{headers:{"plural-forms":"nplurals=2; plural=(n > 1);",language:"en_CA@ashkenazi"},contexts:{"":{Tevet:["Teves"]}}}),z.addLocale("he",L);const D=z.copyLocaleNoNikud(L);z.addLocale("he-x-NoNikud",D);const C=u,O=["","בְּנִיסָן","בְּאִיָיר","בְּסִיוָן","בְּתַמּוּז","בְּאָב","בֶּאֱלוּל","בְּתִשְׁרֵי","בְּחֶשְׁוָן","בְּכִסְלֵו","בְּטֵבֵת","בִּשְׁבָט","בַּאֲדָר","בַּאֲדָר ב׳"];function R(t,e,n){return E(n)+" "+function(t,e){return e===C&&y(t)?"בַּאֲדָר א׳":O[e]}(t,e)+" "+E(t)}const S=function(){const t=new Date;let e=c(t);t.getHours()>19&&e++;const n=function(t){if(h(t,"abs"),(t=Math.trunc(t))<=f)throw new RangeError(`abs2hebrew: ${t} is before epoch`);let e=Math.floor((t-f)/365.24682220597794);for(;d(e)<=t;)++e;--e;let n=t<p(e,1,1)?7:1;for(;t>p(e,n,w(n,e));)++n;return{yy:e,mm:n,dd:1+t-p(e,n,1)}}(e);return R(n.yy,n.mm,n.dd)}();document.write(S)}();
